image: alpine:latest

pipelines:
  default:
    - step:
        script:
          - echo "This script runs on all branches that don't have any specific pipeline assigned in 'branches'."
          - docker version
        services:
          - docker
  branches:
    dev:
      - step:
          name: Build Image
          image: atlassian/pipelines-awscli
          services:
            - docker
          script:
            - apk --update --no-cache add openssh-client
            - echo $(aws ecr get-login --no-include-email --region us-west-2)  > login.sh
            - sh login.sh
            - git submodule init && git submodule update --remote
            - ./deploy.sh build
            - ./deploy.sh push
      - step:
          name: EKS Deploy
          image: atlassian/pipelines-kubectl
          services:
            - docker
          script:
            - apk --update --no-cache add curl openssl git openssh-client jq
            - git clone git@bitbucket.org:sumraprague/bitbucket-cicd.git
            - bitbucket-cicd/deploy.sh kube-init

            - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
            - chmod 700 get_helm.sh
            - bash ./get_helm.sh
            - bitbucket-cicd/deploy.sh set-image
definitions:
  services:
    docker:
      memory: 2048
