version: '3.8'

services:
  {{DEPLOY_NAME}}-app:
    container_name: {{DEPLOY_NAME}}
    image: {{DOCKER_IMAGE}}
    restart: always
    networks:
      - sumra-net
    ports:
      - '8110:80'
      - '18110:443'
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/html/public
#      - WEB_ALIAS_DOMAIN=api.sumrameet.com
      - PHP_DISMOD=apcu,calendar,exif,gd,imagick,imap,ioncube,mongodb,ldap,pcntl,pdo_pgsql,pgsql,shmop,soap,sysvmsg,sysvsem,sysvshm,vips
      - PHP_DISPLAY_ERRORS=1
      - LOG_STDERR=/var/log/vhost-error.log
    volumes:
      - ./web:/var/www/html:rw
#      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:rw
#      - ./conf/.env_local:/app/.env:rw
#    command: /bin/bash -c "php artisan swagger-lume:generate && php artisan queue:listen rabbitmq --queue=SumraMeetMS --timeout=0 > /dev/null"

networks:
  sumra-net:
    name: SumraNet
    driver: bridge
