version: '3.5'

networks:
  app-tier:
    name: sumraNet
    driver: bridge

services:
  apache:
    container_name: {{DEPLOY_NAME}}
#    hostname: nginx
    image: {{DOCKER_IMAGE}}
    networks:
      - app-tier
    ports:
      - '8110:8080'
    volumes:
#      - ./conf/nginx.conf:/opt/sumra/nginx/conf/vhosts/vhosts.conf:ro
#      - ./conf/mime.types:/opt/sumra/nginx/conf/mime.types:ro
#      - ./web/public:/web/public:ro
#      - ./conf/server_blocks.conf:/opt/sumra/nginx/conf/server_blocks/server_blocks.conf:ro
      - ./conf/vhost.conf:/etc/apache2/sites-enabled/000-default.conf:ro
      - ./certs/dev.sumra.net.crt:/certs/dev.sumra.net.crt:ro
      - ./certs/dev.sumra.net.key:/certs/dev.sumra.net.key:ro
      - ./web:/var/www/html:rw
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:rw
#      - ./conf/.env_local:/var/www/html/.env:rw
