version: '3.8'

services:
  {{DEPLOY_NAME}}-app:
    container_name: {{DEPLOY_NAME}}
    image: {{DOCKER_IMAGE}}
    restart: always
    networks:
      - promo-net
    ports:
      - '8110:80'
      - '18110:443'
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/html/public
      - PHP_DISMOD=apcu,calendar,exif,gd,imagick,imap,ioncube,mongodb,ldap,pcntl,pdo_pgsql,pgsql,shmop,soap,sysvmsg,sysvsem,sysvshm,vips
      - PHP_DISPLAY_ERRORS=1
      - LOG_STDERR=/var/log/vhost-error.log
    volumes:
      - ./web:/var/www/html:rw
      - ./logs:/var/log/nginx:rw
#     - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:rw
    #entrypoint: "/bin/bash -c 'while :; do sleep 1m & wait $${!}; php artisan swagger-lume:generate && php artisan queue:listen rabbitmq --queue=Staging.WaitingListsMS --timeout=0 --tries=3; done'"
  #  entrypoint: "/bin/bash -c 'while :; do sleep 1m & wait $${!}; php artisan swagger-lume:generate && php artisan queue:listen rabbitmq --queue=Staging.WaitingListsMS --timeout=0 > /dev/null; done'"

networks:
  promo-net:
    name: PromoNet
    driver: bridge
